# See `maskflow/config.py` for details about parameters.

# Must match the names and index in the JSON annotation file
# of the dataset.
# This setting is convenient to use during inference but not mandatory.
CLASS_NAMES: ["microtubule"]

INPUT:
  # Size of the smallest side of the image during training
  MIN_SIZE_TRAIN: 256
  # Maximum size of the side of the image during training
  MAX_SIZE_TRAIN: 256
  # Size of the smallest side of the image during testing
  MIN_SIZE_TEST: 256
  # Maximum size of the side of the image during testing
  MAX_SIZE_TEST: 256
  # Values to be used for image normalization
  PIXEL_MEAN: [100.0, 100.0, 100.0]
  # Values to be used for image normalization
  PIXEL_STD: [1., 1., 1.]

MODEL:

  BACKBONE:
    # The backbone conv body to use among:
    # R-101-FPN, R-50-FPN and R-50-C4
    CONV_BODY: "R-50-FPN"

  ROI_BOX_HEAD:
    # NUM_CLASSES must include the background class. Its id is 0.
    NUM_CLASSES : 2
    
  ROI_HEADS:
    USE_FPN: True
    
    # Only used durign inference

    # Minimum score threshold (assuming scores in a [0, 1] range); a value chosen to
    # balance obtaining high recall with not having too many low precision
    # detections that will slow down inference post processing steps (like NMS)
    SCORE_THRESH: 0.05
    
    # Overlap threshold used for non-maximum suppression (suppress boxes with
    # IoU >= this threshold)
    NMS: 0.5
    
    # Maximum number of detections to return per image (100 is based on the limit
    # established for the COCO dataset)
    DETECTIONS_PER_IMG: 100
    
  ROI_MASK_HEAD:
    # Resolution of the mask used for segmentation
    # This increase dramatically the model memory usage.
    RESOLUTION: 28

SOLVER:
  MAX_ITER: 3000
  BASE_LR: 0.0025
  STEPS: [2000, 3500]
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 50
  