# See `maskflow/config.py` for details about parameters.

NAME: "Microtubule Detector"
CLASS_NAMES: ["microtubule"]
IMAGE_MAX_DIM: 512
IMAGE_MIN_DIM: 100
IMAGE_MIN_SCALE: 1
IMAGE_RESIZE_MODE: square
MAX_OBJECTS: 200
MEAN_PIXEL: [123.7, 116.8, 103.9]
RPN_ANCHOR_RATIOS: [0.25, 0.33, 0.5, 1, 2, 3, 4]
BACKBONE: "resnet50"
RPN_ANCHOR_SCALES: [32, 64, 128, 256, 512]

