# See `maskflow/config.py` for details about parameters.

NAME: "Microtubule Detector"
CLASS_NAMES: ["microtubule"]
IMAGE_MAX_DIM: 1024
IMAGE_MIN_DIM: 100
IMAGE_MIN_SCALE: 1.0
IMAGE_RESIZE_MODE: square
MAX_GT_INSTANCES: 100
MEAN_PIXEL: [123.7, 116.8, 103.9]
BACKBONE: "resnet50"
