# See `maskflow/config.py` for details about parameters.

NAME: "Microtubule Detector"
CLASS_NAMES: ["microtubule"]
IMAGE_MAX_DIM: 1280
IMAGE_MIN_DIM: 100
IMAGE_MIN_SCALE: 1.0
IMAGE_RESIZE_MODE: square
MEAN_PIXEL: [123.7, 116.8, 103.9]
RPN_ANCHOR_SCALES: [16, 32, 64, 128, 256]
MAX_GT_INSTANCES: 200
TRAIN_ROIS_PER_IMAGE: 200
DETECTION_MAX_INSTANCES: 400
RPN_NMS_THRESHOLD: 0.9
RPN_TRAIN_ANCHORS_PER_IMAGE: 256
BACKBONE: "resnet50"
