dist: xenial
language: c

matrix:
  matrix:
    fast_finish: true

  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libstdc++6

env:
  - PYTHON_VERSION="3.6"
  - PYTHON_VERSION="3.7"

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - echo ". $HOME/miniconda/etc/profile.d/conda.sh" >> $HOME/.bashrc
  - source $HOME/.bashrc
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -n conda_env python=$PYTHON_VERSION
  - conda activate conda_env
  - conda env update -f "environment.yml"
  - pip install --no-deps keras_preprocessing keras_applications tensorflow-estimator tensorflow-datasets
  - pip install --no-deps tf-nightly-2.0-preview tb-nightly

script:
  - conda activate conda_env
  - python setup.py install
  - nosetests -v -s .
