# Usqge: `conda env update -f environment.yml`
channels:
  - conda-forge

dependencies:
    - python>=3.6
    - numpy
    - scipy
    - matplotlib
    - pillow
    - scikit-image
    - scikit-learn
    - tifffile
    - scipy
    - opencv
    - pycocotools
    - tqdm
    - jupyterlab
    - pytest
    - pandas
    - pyyaml
    - pylint
    - mypy
    - importlib_resources
    - pep8
    - requests
    - ipywidgets
    - gpustat
    # Tensorflow dependencies
    - protobuf
    - absl-py
    - gast
    - astor
    - termcolor
    - h5py
    - wrapt
    - keras-preprocessing
    - keras-applications
    - tensorflow-estimator
    # Tensorboard dependencies
    - werkzeug
    - markdown
    - grpcio
    # Tensorflow datasets dependencies
    - promise
    - dill
    #- pip:
        # Install TF deps not available on Conda.
        #- pip install --no-deps -U tensorflow-datasets tensorflow_metadata
        # Install TF (from nightly or not).
        #- pip install --no-deps -U tensorflow-gpu==2.0.0-alpha0 tensorboard
        # or
        #- pip install --no-deps -U tensorflow-cpu==2.0.0-alpha0 tensorboard
        # or
        #- pip install --no-deps -U tf-nightly-gpu-2.0-preview tb-nightly
        # or
        #- pip install --no-deps -U tf-nightly-cpu-2.0-preview tb-nightly

