# Create with `conda env create -f environment.yml`
name: maskflow

channels:
  - pytorch
  - conda-forge

dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pandas
  - opencv
  - tifffile
  - scikit-image
  - scikit-learn
  - ipykernel
  - opencv
  - cython
  - protobuf
  - pyyaml
  - tqdm
  - ipywidgets
  - markdown
  - joblib
  - read-roi
  - pytables
  - pytorch-nightly
  - torchvision
  - importlib_resources
  - pillow
  - yacs
  - tensorboard
  - tensorflow
  - ipyvolume
  - lmfit
  - h5py
  - pycocotools
  - pip:
    # Only for tensorboard
    - https://github.com/facebookresearch/maskrcnn-benchmark/archive/43cb539a62d9ffb292cee4e14c1f38dc16e333a7.zip
    - https://github.com/lanpa/tensorboardX/archive/d56cc06d452e6e9faf2e9cfb071e8525a57c7624.zip
