# Create with `conda env create -f environment.yml`
name: nn

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - pandas
  - opencv
  - tifffile
  - scikit-image
  - scikit-learn
  - ipykernel
  - opencv
  - cython
  - protobuf
  - pyyaml
  - tqdm
  - ipywidgets
  - markdown
  - joblib
  - read-roi
  - pytables
  - tensorboard
  - pytorch-nightly
  - torchvision
  - pip:
    - pycocotools
    - https://github.com/facebookresearch/maskrcnn-benchmark/archive/3308cd926bacef22bc907d508d624580245cc0d1.zip
