# Create with `conda env create -f environment.yml`
name: maskflow

channels:
  - pytorch
  - conda-forge

dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pandas
  - opencv
  - tifffile
  - scikit-image
  - scikit-learn
  - ipykernel
  - opencv
  - cython
  - protobuf
  - pyyaml
  - tqdm
  - ipywidgets
  - markdown
  - joblib
  - read-roi
  - pytables
  - tensorboard
  - pytorch-nightly
  - torchvision
  - importlib_resources
  - pillow
  - yacs
  - pip:
    - pycocotools
    - https://github.com/facebookresearch/maskrcnn-benchmark/archive/4a333692eaf6b3e5118ed2169a9c57b05ef82ede.zip
