# Usqge: `conda env update -f environment.yml`
channels:
  - conda-forge
  
dependencies:
    - python>=3.6
    - numpy
    - scipy
    - matplotlib
    - pillow
    - scikit-image
    - scikit-learn
    - tifffile
    - scipy
    - opencv
    - pycocotools
    - tqdm
    - pip:
      - tensorflow==2.0.0-alpha0
      - tensorboard
