# Usqge: `conda env update -f environment.yml`
channels:
  - conda-forge

dependencies:
    - python>=3.6
    - numpy
    - scipy
    - matplotlib
    - pillow
    - scikit-image
    - scikit-learn
    - tifffile
    - scipy
    - opencv
    - pycocotools
    - tqdm
    - jupyterlab
    - nose
    - pandas
    - pyyaml
    - pylint
    - mypy
    # Tensorflow dependencies
    - protobuf
    - absl-py
    - gast
    - astor
    - termcolor
    - h5py
    - wrapt
    # Tensorboard dependencies
    - werkzeug
    - markdown
    - grpcio
    #- pip:
        #- pip install --no-deps keras_preprocessing keras_applications tensorflow-estimator tensorflow-datasets
        #- pip install --no-deps tensorflow==2.0.0-alpha0 tensorboard
        # or
        #- pip install --no-deps tensorflow-gpu==2.0.0-alpha0 tensorboard
        # or
        #- pip install --no-deps tf-nightly-cpu-2.0-preview tb-nightly
        # or
        #- pip install --no-deps tf-nightly-2.0-preview tb-nightly
