BACKBONE: resnet50
BACKBONE_STRIDES: [4, 8, 16, 32, 64]
BBOX_STD_DEV: [0.1, 0.1, 0.2, 0.2]
CLASS_NAMES: ["nucleus"]
IMAGE_MAX_DIM: 256
IMAGE_MIN_DIM: 256
IMAGE_MIN_SCALE: 0.0
IMAGE_RESIZE_MODE: square
MAX_GT_INSTANCES: 100
MAX_OBJECTS: 100
MEAN_PIXEL: [123.7, 116.8, 103.9]
NAME: Synthetic_Cells
NORMALIZE_IMAGE: false
POST_NMS_ROIS_INFERENCE: 1000
POST_NMS_ROIS_TRAINING: 2000
RPN_ANCHOR_RATIOS: [0.5, 1, 2]
RPN_ANCHOR_SCALES: [32, 64, 128, 256, 512]
RPN_ANCHOR_STRIDE: 1
RPN_BBOX_STD_DEV: [0.1, 0.1, 0.2, 0.2]
RPN_NMS_THRESHOLD: 0.7
TOP_DOWN_PYRAMID_SIZE: 256
TRAIN_BN: false
USE_RPN_ROIS: true
