# See `maskflow/config.py` for details about parameters.

INPUT:
  # Size of the smallest side of the image during training
  MIN_SIZE_TRAIN: 128
  # Maximum size of the side of the image during training
  MAX_SIZE_TRAIN: 256
  # Size of the smallest side of the image during testing
  MIN_SIZE_TEST: 128
  # Maximum size of the side of the image during testing
  MAX_SIZE_TEST: 256

MODEL:
  ROI_BOX_HEAD:
    POOLER_RESOLUTION : 7
    POOLER_SAMPLING_RATIO : 2
    POOLER_SCALES : [0.25, 0.125, 0.0625, 0.03125]
    NUM_CLASSES : 2

  ROI_MASK_HEAD:
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: [0.25, 0.125, 0.0625, 0.03125]
    RESOLUTION: 28

SOLVER:
  MAX_ITER: 90000
  BASE_LR: 0.02
  BIAS_LR_FACTOR: 2
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
  GAMMA: 0.1
  STEPS: [60000, 80000]
  # Number of images per batch
  # This is global, so if we have 8 GPUs and IMS_PER_BATCH = 16, each GPU will
  # see 2 images per batch
  IMS_PER_BATCH: 4
