# See `maskflow/config.py` for details about parameters.

DATASET:
  CLASS_NAMES: ["circle", "triangle", "square"]
  
  IMAGE_SIZE: 128
  
  # Values to be used for image normalization
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  
  # Values to be used for image normalization
  PIXEL_STD: [1., 1., 1.]
  
MODEL:

  BACKBONE:
    NAME: "resnet"
    RESNET_DEPTH: 50
    MIN_LEVEL: 3
    MAX_LEVEL: 7
    
  FPN:
    NUM_SCALES: 3
    ASPECT_RATIOS: [[1.0, 1.0], [1.4, 0.7], [0.7, 1.4]]

  LOSS:
    CLASSIFICATION:
      ALPHA: 0.5
      GAMMA: 1.5
    LOCALIZATION:
      DELTA: 0.1
      BOX_LOSS_WEIGHT: 50.0
  
OPTIMIZER:
  MOMENTUM: 0.9
  LEARNING_RATE: 0.08
  LR_WARMUP_INIT: 0.008
  LR_WARMUP_EPOCH: 1.0
  FIRST_LR_DROP_EPOCH: 8.0
  SECOND_LR_DROP_EPOCH: 11.0
  WEIGHT_DECAY: 0.00001
  