BACKBONE: resnet50
BACKBONE_STRIDES: [4, 8, 16, 32, 64]
BBOX_STD_DEV: [0.1, 0.1, 0.2, 0.2]
CLASS_NAMES: [person, bicycle, car, motorcycle, airplane, bus, train, truck, boat,
  traffic light, fire hydrant, stop sign, parking meter, bench, bird, cat, dog, horse,
  sheep, cow, elephant, bear, zebra, giraffe, backpack, umbrella, handbag, tie, suitcase,
  frisbee, skis, snowboard, sports ball, kite, baseball bat, baseball glove, skateboard,
  surfboard, tennis racket, bottle, wine glass, cup, fork, knife, spoon, bowl, banana,
  apple, sandwich, orange, broccoli, carrot, hot dog, pizza, donut, cake, chair, couch,
  potted plant, bed, dining table, toilet, tv, laptop, mouse, remote, keyboard, cell
    phone, microwave, oven, toaster, sink, refrigerator, book, clock, vase, scissors,
  teddy bear, hair drier, toothbrush]
IMAGE_MAX_DIM: 256
IMAGE_MIN_DIM: 256
IMAGE_MIN_SCALE: 0.0
IMAGE_RESIZE_MODE: square
MAX_GT_INSTANCES: 100
MAX_OBJECTS: 100
MEAN_PIXEL: [123.7, 116.8, 103.9]
NAME: COCO
NORMALIZE_IMAGE: false
POST_NMS_ROIS_INFERENCE: 1000
POST_NMS_ROIS_TRAINING: 2000
RPN_ANCHOR_RATIOS: [0.5, 1, 2]
RPN_ANCHOR_SCALES: [32, 64, 128, 256, 512]
RPN_ANCHOR_STRIDE: 1
RPN_BBOX_STD_DEV: [0.1, 0.1, 0.2, 0.2]
RPN_NMS_THRESHOLD: 0.7
TOP_DOWN_PYRAMID_SIZE: 256
TRAIN_BN: false
USE_RPN_ROIS: true
